# Russian translation for duplicity
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the duplicity package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2020-03-07 09:49-0600\n"
"PO-Revision-Date: 2016-10-13 10:34+0000\n"
"Last-Translator: Nicholas Guriev <guriev-ns@ya.ru>\n"
"Language-Team: Russian <ru@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2020-07-09 18:01+0000\n"
"X-Generator: Launchpad (build 4809fcb62f445aaa3ae919f7f6c3cc7d156ea57a)\n"

#: ../bin/duplicity:102
msgid "INT intercepted...exiting."
msgstr "Перехват INT...выполняется выход."

#: ../bin/duplicity:110
#, python-format
msgid "GPG error detail: %s"
msgstr "Подробности ошибки GPG: %s"

#: ../bin/duplicity:120
#, python-format
msgid "User error detail: %s"
msgstr "Сведения ошибки пользователя: %s"

#: ../bin/duplicity:130
#, python-format
msgid "Backend error detail: %s"
msgstr "Подробности об ошибке в заглушке: %s"

#: ../bin/rdiffdir:64 ../duplicity/commandline.py:235
#, python-format
msgid "Error opening file %s"
msgstr "Ошибка открытия файла %s"

#: ../bin/rdiffdir:131
#, python-format
msgid "File %s already exists, will not overwrite."
msgstr "Файл %s уже существует и не будет перезаписан."

#: ../duplicity/asyncscheduler.py:70
#, python-format
msgid "instantiating at concurrency %d"
msgstr "параллельное создание %d"

#: ../duplicity/asyncscheduler.py:97
msgid "inserting barrier"
msgstr "вставка барьера"

#: ../duplicity/asyncscheduler.py:146
msgid "running task synchronously (asynchronicity disabled)"
msgstr "выполнение задачи синхронно (асинхронность выключена)"

#: ../duplicity/asyncscheduler.py:152
msgid "scheduling task for asynchronous execution"
msgstr "Планирование задачи для асинхронного выполнения"

#: ../duplicity/asyncscheduler.py:181
msgid "task completed successfully"
msgstr "задача успешно завершена"

#: ../duplicity/asyncscheduler.py:192
msgid ""
"a previously scheduled task has failed; propagating the result immediately"
msgstr ""
"не удалось выполнить запланированную ранее задачу; выполняется мгновенное "
"распространение результата"

#: ../duplicity/asyncscheduler.py:215 ../duplicity/asyncscheduler.py:236
#, python-format
msgid "active workers = %d"
msgstr "активный обработчики = %d"

#: ../duplicity/asyncscheduler.py:256
#, python-format
msgid "task execution done (success: %s)"
msgstr "завершено выполнение задачи (успех: %s)"

#: ../duplicity/backend.py:102
#, python-format
msgid "Import of %s %s"
msgstr "Импортирование %s %s"

#: ../duplicity/backend.py:211
#, python-format
msgid "Could not initialize backend: %s"
msgstr "Невозможно инициализиовать внутренний интерфейс: %s"

#: ../duplicity/backend.py:390
#, python-format
msgid "Backtrace of previous error: %s"
msgstr ""

#: ../duplicity/backend.py:406
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr ""

#: ../duplicity/backend.py:410
#, python-format
msgid "Attempt %s failed. %s: %s"
msgstr "Попытка %s произошла с ошибкой. %s: %s"

#: ../duplicity/backend.py:504
#, python-format
msgid "Reading results of '%s'"
msgstr "Чтение результата '%s'"

#: ../duplicity/backend.py:530
#, python-format
msgid "Writing %s"
msgstr "Записывается %s"

#: ../duplicity/backend.py:571
#, python-format
msgid "File %s not found locally after get from backend"
msgstr ""

#: ../duplicity/backends/giobackend.py:109
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Не удалось подключиться, проверьте пароль: %s"

#: ../duplicity/backends/multibackend.py:96
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:105
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:110
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:160
#: ../duplicity/backends/multibackend.py:165
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:176
#, python-format
msgid "MultiBackend: Url %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:180
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:189
#, python-format
msgid "MultiBackend: use store %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:194
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:207
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:248
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr ""

#: ../duplicity/backends/multibackend.py:261
#, python-format
msgid ""
"MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:268
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr ""

#: ../duplicity/backends/multibackend.py:275
#, python-format
msgid ""
"MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:294
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:297
#, python-format
msgid ""
"MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:307
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr ""

#: ../duplicity/backends/multibackend.py:310
#, python-format
msgid "Exception during list of %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:317
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:345
#, python-format
msgid "MultiBackend: failed to delete %s from %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:349
#, python-format
msgid ""
"MultiBackend: failed to delete %s. Tried all backing stores and none "
"succeeded"
msgstr ""

#: ../duplicity/backends/pydrivebackend.py:150
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:66
msgid "Missing socket or ssl python modules."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:84
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:105
msgid ""
"Option '--ssl-cacert-path' is not supported with python 2.7.8 and below."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:109
#, python-format
msgid ""
"For certificate verification with python 2.7.8 or earlier a cacert database\n"
"file is needed in one of these locations: %s\n"
"Hints:\n"
"Consult the man page, chapter 'SSL Certificate Verification'.\n"
"Consider using the options --ssl-cacert-file, --ssl-no-check-certificate ."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:155
#, python-format
msgid "Using WebDAV protocol %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:156
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:158
#, python-format
msgid "Using WebDAV directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:189
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:200
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:219
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:220
#: ../duplicity/backends/webdavbackend.py:243
#, python-format
msgid "WebDAV data length: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:223
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:229
#, python-format
msgid "WebDAV redirect to: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:231
msgid "WebDAV redirected 10 times. Giving up."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:236
msgid "WebDAV missing location header in redirect response."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:241
msgid "WebDAV retry request with authentification headers."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:242
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:246
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:263
msgid ""
"python-kerberos needed to use kerberos                           "
"authorization, falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:267
#, python-format
msgid ""
"Kerberos authorization failed: %s.                          Falling back to "
"basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:365
#, python-format
msgid "Creating missing directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:369
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:382
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:427
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:449
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:469
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr ""

#: ../duplicity/commandline.py:78
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"Use of default filenames is strongly suggested."
msgstr ""
"Внимание: возможность %s почти устарела и будет выведена из эксплуатации в "
"следующем выпуске.\n"
"Настоятельно предлагаем использовать предложенные имена файлов."

#: ../duplicity/commandline.py:85
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"--include-filelist and --exclude-filelist now accept globbing characters and "
"should be used instead."
msgstr ""

#: ../duplicity/commandline.py:95
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"On many GNU/Linux systems, stdin is represented by /dev/stdin and\n"
"--include-filelist=/dev/stdin or --exclude-filelist=/dev/stdin could\n"
"be used as a substitute."
msgstr ""

#. TRANSL: Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/commandline.py:256 ../duplicity/commandline.py:266
#: ../duplicity/commandline.py:287 ../duplicity/commandline.py:358
#: ../duplicity/commandline.py:376 ../duplicity/commandline.py:608
#: ../duplicity/commandline.py:641 ../duplicity/commandline.py:854
msgid "path"
msgstr "путь"

#. TRANSL: Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#. TRANSL: Used in usage help to represent an ID for a hidden GnuPG key. Example:
#. --hidden-encrypt-key <gpg_key_id>
#. TRANSL: Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/commandline.py:282 ../duplicity/commandline.py:289
#: ../duplicity/commandline.py:382 ../duplicity/commandline.py:592
#: ../duplicity/commandline.py:827
msgid "gpg-key-id"
msgstr "gpg-key-id"

#. TRANSL: Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/commandline.py:297 ../duplicity/commandline.py:407
#: ../duplicity/commandline.py:877
msgid "shell_pattern"
msgstr "shell_pattern"

#. TRANSL: Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/commandline.py:303 ../duplicity/commandline.py:312
#: ../duplicity/commandline.py:319 ../duplicity/commandline.py:409
#: ../duplicity/commandline.py:416 ../duplicity/commandline.py:429
#: ../duplicity/commandline.py:823
msgid "filename"
msgstr "имя файла"

#. TRANSL: Used in usage help to represent a regular expression (regexp).
#: ../duplicity/commandline.py:326 ../duplicity/commandline.py:420
msgid "regular_expression"
msgstr "regular_expression"

#. TRANSL: Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/commandline.py:330 ../duplicity/commandline.py:370
#: ../duplicity/commandline.py:496 ../duplicity/commandline.py:909
msgid "time"
msgstr "время"

#. TRANSL: Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:378 ../duplicity/commandline.py:476
#: ../duplicity/commandline.py:499 ../duplicity/commandline.py:600
#: ../duplicity/commandline.py:842
msgid "options"
msgstr "параметры"

#: ../duplicity/commandline.py:393
#, python-format
msgid ""
"Running in 'ignore errors' mode due to %s; please re-consider if this was "
"not intended"
msgstr ""
"Выполнение в режиме 'пропуска ошибок' в связи с %s; пожалуйста, пересмотрите "
"решение, если это не было намерением"

#. TRANSL: Used in usage help to represent an imap mailbox
#: ../duplicity/commandline.py:405
msgid "imap_mailbox"
msgstr "imap_mailbox"

#: ../duplicity/commandline.py:423
msgid "file_descriptor"
msgstr "file_descriptor"

#. TRANSL: Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/commandline.py:434 ../duplicity/commandline.py:456
#: ../duplicity/commandline.py:473 ../duplicity/commandline.py:482
#: ../duplicity/commandline.py:532 ../duplicity/commandline.py:537
#: ../duplicity/commandline.py:541 ../duplicity/commandline.py:560
#: ../duplicity/commandline.py:566 ../duplicity/commandline.py:570
#: ../duplicity/commandline.py:636 ../duplicity/commandline.py:837
msgid "number"
msgstr "количество"

#. TRANSL: Used in usage help (noun)
#: ../duplicity/commandline.py:437
msgid "backup name"
msgstr "название резервной копии"

#: ../duplicity/commandline.py:555
msgid "policy"
msgstr ""

#: ../duplicity/commandline.py:573
msgid "Hot|Cool|Archive"
msgstr ""

#. TRANSL: noun
#: ../duplicity/commandline.py:576 ../duplicity/commandline.py:579
#: ../duplicity/commandline.py:808
msgid "command"
msgstr "команда"

#: ../duplicity/commandline.py:582
msgid "pyrax|cloudfiles"
msgstr ""

#: ../duplicity/commandline.py:603
msgid "pem formatted bundle of certificate authorities"
msgstr ""

#: ../duplicity/commandline.py:604
msgid "path to a folder with certificate authority files"
msgstr ""

#. TRANSL: Used in usage help. Example:
#. --timeout <seconds>
#. TRANSL: Used in usage help. Example:
#. --backend-retry-delay <seconds>
#. TRANSL: Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/commandline.py:613 ../duplicity/commandline.py:647
#: ../duplicity/commandline.py:871
msgid "seconds"
msgstr "секунды"

#. TRANSL: abbreviation for "character" (noun)
#: ../duplicity/commandline.py:619 ../duplicity/commandline.py:805
msgid "char"
msgstr "символ"

#: ../duplicity/commandline.py:771
#, python-format
msgid "Using archive dir: %s"
msgstr "Использование каталога архива: %s"

#: ../duplicity/commandline.py:772
#, python-format
msgid "Using backup name: %s"
msgstr "Использование наименования резервной копии: %s"

#: ../duplicity/commandline.py:779
#, python-format
msgid "Command line error: %s"
msgstr "Ошибка в командной строке: %s"

#: ../duplicity/commandline.py:780
msgid "Enter 'duplicity --help' for help screen."
msgstr "Введите  'duplicity --help' для экрана справки."

#. TRANSL: Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/commandline.py:793
msgid "absolute_path"
msgstr "полный_путь"

#. TRANSL: Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/commandline.py:797
msgid "alias"
msgstr "псевдоним"

#. TRANSL: Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:802
msgid "bucket_name"
msgstr "bucket_name"

#. TRANSL: Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/commandline.py:813
msgid "container_name"
msgstr "container_name"

#. TRANSL: noun
#: ../duplicity/commandline.py:816
msgid "count"
msgstr "количество"

#. TRANSL: Used in usage help to represent the name of a file directory
#: ../duplicity/commandline.py:819
msgid "directory"
msgstr "каталог"

#. TRANSL: Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/commandline.py:832
msgid "module"
msgstr "модуль"

#. TRANSL: Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:846
msgid "other.host"
msgstr "other.host"

#. TRANSL: Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:850
msgid "password"
msgstr "пароль"

#. TRANSL: Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:858
msgid "port"
msgstr "порт"

#. TRANSL: Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:863
msgid "prefix"
msgstr "префикс"

#. TRANSL: Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/commandline.py:867
msgid "relative_path"
msgstr "относительный_путь"

#. TRANSL: Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/commandline.py:882
msgid "some_dir"
msgstr "некоторый_каталог"

#. TRANSL: Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:888
msgid "source_dir"
msgstr "source_dir"

#. TRANSL: Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:893
msgid "source_url"
msgstr "source_url"

#. TRANSL: Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:899
msgid "target_dir"
msgstr "target_dir"

#. TRANSL: Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:904
msgid "target_url"
msgstr "target_url"

#. TRANSL: Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:914
msgid "user"
msgstr "пользователь"

#. TRANSL: account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/commandline.py:917
msgid "account_id"
msgstr ""

#. TRANSL: application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/commandline.py:921
msgid "application_key"
msgstr ""

#. TRANSL: remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/commandline.py:925 ../duplicity/dup_collections.py:508
msgid "remote"
msgstr "удалённая"

#. TRANSL: Header in usage help
#: ../duplicity/commandline.py:944
msgid "Backends and their URL formats:"
msgstr "Заглушки и формат их URL:"

#. TRANSL: Header in usage help
#: ../duplicity/commandline.py:977
msgid "Commands:"
msgstr "Команды:"

#: ../duplicity/commandline.py:1002
#, python-format
msgid ""
"Specified archive directory '%s' does not exist, or is not a directory"
msgstr "Заданная папка архива '%s' не существует или не является папкой"

#: ../duplicity/commandline.py:1011
#, python-format
msgid ""
"Sign key should be an 8, 16 alt. 40 character hex string, like 'AA0E73D2'.\n"
"Received '%s' instead."
msgstr ""

#: ../duplicity/commandline.py:1071
#, python-format
msgid ""
"Restore destination directory %s already exists.\n"
"Will not overwrite."
msgstr ""
"Каталог в который предназначено восстановление %s уже существует.\n"
"Замена не будет произведена."

#: ../duplicity/commandline.py:1076
#, python-format
msgid "Verify directory %s does not exist"
msgstr "Убедитесь, что папка %s не существует"

#: ../duplicity/commandline.py:1082
#, python-format
msgid "Backup source directory %s does not exist."
msgstr "Папка источника резервной копии %s не существует."

#: ../duplicity/commandline.py:1113
#, python-format
msgid "Command line warning: %s"
msgstr "Предупреждение командной строки: %s"

#: ../duplicity/commandline.py:1113
msgid ""
"Selection options --exclude/--include\n"
"currently work only when backing up,not restoring."
msgstr ""
"Параметры выбора --exclude/--include\n"
"в настоящее время работают только для резервного копирования, не для "
"восстановления."

#: ../duplicity/commandline.py:1149
#, python-format
msgid "GPG binary is %s, version %s"
msgstr ""

#: ../duplicity/commandline.py:1176
#, python-format
msgid ""
"Bad URL '%s'.\n"
"Examples of URL strings are \"scp://user@host.net:1234/path\" and\n"
"\"file:///usr/local\".  See the man page for more information."
msgstr ""
"Недопустимая адресная ссылка URL '%s'.\n"
"Например: \"scp://user@host.net:1234/path\" и\n"
"\"file:///usr/local\".  Для получения дополнительных сведений обратитесь в "
"руководству (man)."

#: ../duplicity/commandline.py:1206
msgid "Main action: "
msgstr "Главное действие: "

#: ../duplicity/diffdir.py:115 ../duplicity/diffdir.py:418
#, python-format
msgid "Error %s getting delta for %s"
msgstr "Ошибка %s при получении различий для %s"

#: ../duplicity/diffdir.py:130
#, python-format
msgid "Getting delta of %s and %s"
msgstr "Приём дельты %s и %s"

#: ../duplicity/diffdir.py:181
#, python-format
msgid "A %s"
msgstr "Д %s"

#: ../duplicity/diffdir.py:188
#, python-format
msgid "M %s"
msgstr "И %s"

#: ../duplicity/diffdir.py:210
#, python-format
msgid "Comparing %s and %s"
msgstr "Сравнение %s и %s"

#: ../duplicity/diffdir.py:218
#, python-format
msgid "D %s"
msgstr "У %s"

#: ../duplicity/dup_collections.py:177 ../duplicity/dup_collections.py:191
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr ""

#: ../duplicity/dup_collections.py:216
msgid "Fatal Error: No manifests found for most recent backup"
msgstr ""
"Критическая ошибка: отсутствуют манифесты для недавней резервной копии"

#: ../duplicity/dup_collections.py:225
msgid ""
"Fatal Error: Remote manifest does not match local one.  Either the remote "
"backup set or the local archive directory has been corrupted."
msgstr ""
"Критическая ошибка: Удалённый манифест не соответствует локальному. "
"Неисправен удалённый набор резервного копирования или папка локального "
"архива."

#: ../duplicity/dup_collections.py:233
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr ""
"Критическая ошибка: Нет доступа к чтению удалённого и локального манифеста."

#: ../duplicity/dup_collections.py:244
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr ""

#: ../duplicity/dup_collections.py:256
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr ""

#: ../duplicity/dup_collections.py:259
#, python-format
msgid "Processing remote manifest %s (%s)"
msgstr ""

#: ../duplicity/dup_collections.py:355
msgid "Preferring Backupset over previous one!"
msgstr "Предпочтение набора резервного копирования вместо предыдущего!"

#: ../duplicity/dup_collections.py:358
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr ""
"Пропуск инкрементального  набора резервного копирования (время_запуска: %s; "
"необходимо: %s)"

#: ../duplicity/dup_collections.py:363
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr ""
"Добавлена пошаговая резервная копия (время_начала: %s / время_конца: %s)"

#: ../duplicity/dup_collections.py:433
msgid "Chain start time: "
msgstr "Цепочка начата: "

#: ../duplicity/dup_collections.py:434
msgid "Chain end time: "
msgstr "Цепочка завершена: "

#: ../duplicity/dup_collections.py:435
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "Количество содержащихся наборов резервного копирования: %d"

#: ../duplicity/dup_collections.py:437
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Общее число содержащихся томов: %d"

#: ../duplicity/dup_collections.py:439 ../duplicity/dup_collections.py:1228
msgid "Type of backup set:"
msgstr "Тип резервной копии:"

#: ../duplicity/dup_collections.py:439 ../duplicity/dup_collections.py:1228
msgid "Time:"
msgstr "Время:"

#: ../duplicity/dup_collections.py:439
msgid "Num volumes:"
msgstr "Число томов:"

#: ../duplicity/dup_collections.py:443 ../duplicity/dup_collections.py:1234
msgid "Full"
msgstr "Полная"

#: ../duplicity/dup_collections.py:446 ../duplicity/dup_collections.py:1236
msgid "Incremental"
msgstr "Пошаговая"

#: ../duplicity/dup_collections.py:506
msgid "local"
msgstr "Локальная"

#: ../duplicity/dup_collections.py:663
msgid "Collection Status"
msgstr "Состояние сбора"

#: ../duplicity/dup_collections.py:665
#, python-format
msgid "Connecting with backend: %s"
msgstr "Соединение с внутренним интерфейсом: %s"

#: ../duplicity/dup_collections.py:667
#, python-format
msgid "Archive dir: %s"
msgstr "Папка архива: %s"

#: ../duplicity/dup_collections.py:670
#, python-format
msgid "Found %d secondary backup chain."
msgid_plural "Found %d secondary backup chains."
msgstr[0] "Найдена %d вторичная цепочка резервных копий."
msgstr[1] "Найдены %d вторичные цепочки резервных копий."
msgstr[2] "Найдено %d вторичных цепочек резервных копий."

#: ../duplicity/dup_collections.py:675
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Вторичная цепочка %d из %d:"

#: ../duplicity/dup_collections.py:681
msgid "Found primary backup chain with matching signature chain:"
msgstr ""
"Найдена первичная цепочка резервного копирования с соответствующей цепочкой "
"подписи:"

#: ../duplicity/dup_collections.py:685
msgid "No backup chains with active signatures found"
msgstr ""
"Отсутствуют цепочки резервного копирования с найденными, задействованными "
"подписями"

#: ../duplicity/dup_collections.py:688
#, python-format
msgid "Also found %d backup set not part of any chain,"
msgid_plural "Also found %d backup sets not part of any chain,"
msgstr[0] ""
"Также найден %d набор резервного копирования, не являющегося частью ни одной "
"цепочки,"
msgstr[1] ""
"Также найдены %d набора резервного копирования, не являющихся частью ни "
"одной цепочки,"
msgstr[2] ""
"Также найдены %d наборов резервного копирования, не являющихся частью ни "
"одной цепочки,"

#: ../duplicity/dup_collections.py:692
#, python-format
msgid "and %d incomplete backup set."
msgid_plural "and %d incomplete backup sets."
msgstr[0] "а также %d неполный набор резервного копирования."
msgstr[1] "а также %d неполных набора резервного копирования."
msgstr[2] "а также %d неполных наборов резервного копирования."

#. TRANSL: "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:697
msgid ""
"These may be deleted by running duplicity with the \"cleanup\" command."
msgstr ""
"Это может быть удалено с помощью запуска duplicity с командой \"cleanup\"."

#: ../duplicity/dup_collections.py:700
msgid "No orphaned or incomplete backup sets found."
msgstr ""
"Отсутствуют изолированные или неполные наборы резервного копирования."

#: ../duplicity/dup_collections.py:716
#, python-format
msgid "%d file exists on backend"
msgid_plural "%d files exist on backend"
msgstr[0] "%d файл существует во внутреннем интерфейсе"
msgstr[1] "%d файлов существует во внутреннем интерфейсе"
msgstr[2] "%d файлов существует во внутреннем интерфейсе"

#: ../duplicity/dup_collections.py:726
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] "%d файл существует во временных файлах"
msgstr[1] "%d файла существует во временных файлах"
msgstr[2] "%d файлов существует во временных файлах"

#: ../duplicity/dup_collections.py:779
msgid ""
"Warning, discarding last backup set, because of missing signature file."
msgstr ""
"Внимание, отозван последний набор резервного копирования, в связи с "
"отсутствием файла подписи."

#: ../duplicity/dup_collections.py:802
msgid "Warning, found the following local orphaned signature file:"
msgid_plural "Warning, found the following local orphaned signature files:"
msgstr[0] "Внимание, найден следующий локальный изолированный файл подписи:"
msgstr[1] ""
"Внимание, найдены следующие локальные изолированные файлы подписей:"
msgstr[2] ""
"Внимание, найдены следующие локальные изолированные файлы подписей:"

#: ../duplicity/dup_collections.py:811
msgid "Warning, found the following remote orphaned signature file:"
msgid_plural "Warning, found the following remote orphaned signature files:"
msgstr[0] "Внимание, найден следующий удалённый изолированный файл подписи:"
msgstr[1] ""
"Внимание, найдены следующие удалённые изолированные файлы подписей:"
msgstr[2] ""
"Внимание, найдены следующие удалённые изолированные файлы подписей:"

#: ../duplicity/dup_collections.py:820
msgid "Warning, found signatures but no corresponding backup files"
msgstr ""
"Внимание, найдены подписи, которые не соответствуют с файлами резервной копии"

#: ../duplicity/dup_collections.py:824
msgid ""
"Warning, found incomplete backup sets, probably left from aborted session"
msgstr ""
"Внимание, обнаружены незавершённые наборы резервных копий, возможно они "
"остались от прерванного сеанса"

#: ../duplicity/dup_collections.py:828
msgid "Warning, found the following orphaned backup file:"
msgid_plural "Warning, found the following orphaned backup files:"
msgstr[0] ""
"Внимание, найден следующий изолированный файл резервного копирования:"
msgstr[1] ""
"Внимание, найдены следующие изолированные файлы резервного копирования:"
msgstr[2] ""
"Внимание, найдены следующие изолированные файлы резервного копирования:"

#: ../duplicity/dup_collections.py:845
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "Извлечение цепочек резервного копирования из списка файлов: %s"

#: ../duplicity/dup_collections.py:857
#, python-format
msgid "File %s is part of known set"
msgstr "Файл %s является частью известного набора"

#: ../duplicity/dup_collections.py:860
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr "Файл %s не является частью известного набора; создаётся новый набор"

#: ../duplicity/dup_collections.py:865
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "Пропуск файла (отклонено набором резервного копирования) '%s'"

#: ../duplicity/dup_collections.py:881
#, python-format
msgid "Found backup chain %s"
msgstr "Найдена резервная копия %s"

#: ../duplicity/dup_collections.py:886
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "Добавление набора %s для ранее существующей цепочки %s"

#: ../duplicity/dup_collections.py:890
#, python-format
msgid "Found orphaned set %s"
msgstr "Обнаружен изолированный набор %s"

#: ../duplicity/dup_collections.py:1040
#, python-format
msgid ""
"No signature chain for the requested time. Using oldest available chain, "
"starting at time %s."
msgstr ""

#: ../duplicity/dup_collections.py:1226
#, python-format
msgid "File: %s"
msgstr "Файл: %s"

#: ../duplicity/dup_collections.py:1227
#, python-format
msgid "Total number of backup: %d"
msgstr "Общее количество резервного копирования: %d"

#: ../duplicity/dup_collections.py:1228
msgid "Type of file change:"
msgstr "Тип изменения файла:"

#: ../duplicity/dup_main.py:111
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "Повторное использование настроенного PASSPHRASE как SIGN_PASSPHRASE"

#: ../duplicity/dup_main.py:118
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "Повторное использование настроенного SIGN_PASSPHRASE как PASSPHRASE"

#: ../duplicity/dup_main.py:157
msgid "PASSPHRASE variable not set, asking user."
msgstr "Переменная PASSPHRASE не назначена, выполняется запрос пользователя."

#: ../duplicity/dup_main.py:172
msgid "GnuPG passphrase for signing key:"
msgstr "Кодовая фраза GnuPG для подписывающего ключа:"

#: ../duplicity/dup_main.py:177
msgid "GnuPG passphrase:"
msgstr "Кодовая фраза GnuPG:"

#: ../duplicity/dup_main.py:182
msgid "Retype passphrase for signing key to confirm: "
msgstr "Введите повторно кодовую фразу для подписывающего ключа: "

#: ../duplicity/dup_main.py:184
msgid "Retype passphrase to confirm: "
msgstr "Введите кодовую фразу для подтверждения снова: "

#: ../duplicity/dup_main.py:187
msgid "First and second passphrases do not match!  Please try again."
msgstr ""
"Первая и вторая кодовая фраза не совпадают! Пожалуйста, повторите снова."

#: ../duplicity/dup_main.py:194
msgid ""
"Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr ""
"Невозможно использовать пустую кодовую фразу с симметричным шифрованием!  "
"Пожалуйста, повторите снова."

#: ../duplicity/dup_main.py:251
#, python-format
msgid ""
"File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"Файл %s уже имеется в наборе резервного копирования.\n"
"Продолжение перезапуска на файле %s."

#: ../duplicity/dup_main.py:260
#, python-format
msgid ""
"File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"Файл %s отсутствует в наборе резервного копирования.\n"
"Продолжение перезапуска на файле %s."

#: ../duplicity/dup_main.py:309
#, python-format
msgid "File %s was corrupted during upload."
msgstr "Файл %s был повреждён во время выгрузки."

#: ../duplicity/dup_main.py:349
msgid ""
"Restarting backup, but current encryption settings do not match original "
"settings"
msgstr ""
"Перезапуск резервного копирования, но настройки текущего шифрования не "
"соответствуют исходным настройкам"

#: ../duplicity/dup_main.py:372
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr ""

#: ../duplicity/dup_main.py:442
#, python-format
msgid "Processed volume %d"
msgstr ""

#: ../duplicity/dup_main.py:592
msgid ""
"Fatal Error: Unable to start incremental backup.  Old signatures not found "
"and incremental specified"
msgstr ""
"Фатальная ошибка: Не удалось начать пошаговое резервное копирование. Старая "
"сигнатура не найдена и указан пошаговый режим"

#: ../duplicity/dup_main.py:596
msgid "No signatures found, switching to full backup."
msgstr "Сигнатуры не найдены, переключение на полную резервную копию."

#: ../duplicity/dup_main.py:610
msgid "Backup Statistics"
msgstr "Статистика резервного копирования"

#: ../duplicity/dup_main.py:716
#, python-format
msgid "%s not found in archive - no files restored."
msgstr "%s не найден в архиве, нет восстановленных файлов."

#: ../duplicity/dup_main.py:720
msgid "No files found in archive - nothing restored."
msgstr "Ничего не найдено в архиве - ничего не восстановлено."

#: ../duplicity/dup_main.py:753
#, python-format
msgid "Processed volume %d of %d"
msgstr "Обработан том %d из %d"

#: ../duplicity/dup_main.py:787
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "Недопустимые данные - %s hash не соответствует файлу:"

#: ../duplicity/dup_main.py:790
#, python-format
msgid "Calculated hash: %s"
msgstr "Вычисленный хэш: %s"

#: ../duplicity/dup_main.py:791
#, python-format
msgid "Manifest hash: %s"
msgstr "Хеш манифеста: %s"

#: ../duplicity/dup_main.py:834
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "Том был подписан ключом %s, а не %s"

#: ../duplicity/dup_main.py:866
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Проверка завершена: %s, %s."

#: ../duplicity/dup_main.py:867
#, python-format
msgid "%d file compared"
msgid_plural "%d files compared"
msgstr[0] "%d файл сравнён"
msgstr[1] "%d файла сравнены"
msgstr[2] "%d файлов сравнено"

#: ../duplicity/dup_main.py:869
#, python-format
msgid "%d difference found"
msgid_plural "%d differences found"
msgstr[0] "%d отличие найдено"
msgstr[1] "%d отличия найдено"
msgstr[2] "%d отличий найдено"

#: ../duplicity/dup_main.py:888
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "Посторонних файлов не найдено, при очистке ничего не удалено."

#: ../duplicity/dup_main.py:893
msgid "Deleting this file from backend:"
msgid_plural "Deleting these files from backend:"
msgstr[0] "Удаляется следующий файл из заглушки:"
msgstr[1] "Удаляются следующие файлы из заглушки:"
msgstr[2] "Удаляются следующие файлы из заглушки:"

#: ../duplicity/dup_main.py:904
msgid "Found the following file to delete:"
msgid_plural "Found the following files to delete:"
msgstr[0] "Найден файл для удаления:"
msgstr[1] "Найдены файлы для удаления:"
msgstr[2] "Найдены файлы для удаления:"

#: ../duplicity/dup_main.py:907
msgid "Run duplicity again with the --force option to actually delete."
msgstr ""
"Запустите duplicity ещё раз с ключом --force чтобы удалить на самом деле."

#: ../duplicity/dup_main.py:950
msgid "There are backup set(s) at time(s):"
msgstr "Есть резервные копии за следующие даты:"

#: ../duplicity/dup_main.py:952
msgid "Which can't be deleted because newer sets depend on them."
msgstr "Какие не могут быть удалены из-за новых наборов зависящих от них."

#: ../duplicity/dup_main.py:956
msgid ""
"Current active backup chain is older than specified time.  However, it will "
"not be deleted.  To remove all your backups, manually purge the repository."
msgstr ""
"Текущая активная цепочка резервных копий старее чем указанное время.  Те не "
"менее, она не будет удалена. Чтобы удалить все резервные копии, вручную "
"очистите хранилище."

#: ../duplicity/dup_main.py:969
msgid "No old backup sets found, nothing deleted."
msgstr "Старые резервные копии не найдены, ничего не удалено."

#: ../duplicity/dup_main.py:972
msgid "Deleting backup chain at time:"
msgid_plural "Deleting backup chains at times:"
msgstr[0] "Удаление цепочки резервных копий по времени:"
msgstr[1] "Удаление цепочек резервных копий по времени:"
msgstr[2] "Удаление цепочек резервных копий по времени:"

#: ../duplicity/dup_main.py:984
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:986
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr ""

#: ../duplicity/dup_main.py:989
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "Удаление всей цепочки подписей %s"

#: ../duplicity/dup_main.py:991
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "Удаление полной цепочки резервных копий  %s"

#: ../duplicity/dup_main.py:997
msgid "Found old backup chain at the following time:"
msgid_plural "Found old backup chains at the following times:"
msgstr[0] "Обнаружена цепочка резервных копий, выполненных:"
msgstr[1] "Обнаружены цепочки резервных копий, выполненных:"
msgstr[2] "Обнаружены цепочки резервных копий, выполненных:"

#: ../duplicity/dup_main.py:1001
msgid "Rerun command with --force option to actually delete."
msgstr "Rerun command with --force option to actually delete."

#: ../duplicity/dup_main.py:1024
msgid "No old backup sets found."
msgstr ""

#: ../duplicity/dup_main.py:1039
#, python-format
msgid "Signature %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1046 ../duplicity/dup_main.py:1085
#, python-format
msgid "Replicating %s."
msgstr ""

#: ../duplicity/dup_main.py:1073
#, python-format
msgid "Backupset %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1221
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr ""
"Удаление локального %s (недостаточно надёжный во внутреннем интерфейсе)."

#: ../duplicity/dup_main.py:1226
#, python-format
msgid "Unable to delete %s: %s"
msgstr "Невозможно удалить %s: %s"

#: ../duplicity/dup_main.py:1260 ../duplicity/dup_temp.py:270
#, python-format
msgid "Failed to read %s: %s"
msgstr "Не удалось прочитать %s: %s"

#: ../duplicity/dup_main.py:1274
#, python-format
msgid "Copying %s to local cache."
msgstr "Копируется %s в локальный кэш."

#: ../duplicity/dup_main.py:1322
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr ""
"Локальные и удалённые метаданные синхронизированы, синхронизация не "
"требуется."

#: ../duplicity/dup_main.py:1327
msgid "Synchronizing remote metadata to local cache..."
msgstr ""
"Синхронизация удалённых метаданных с локальными временными файлами..."

#: ../duplicity/dup_main.py:1340
msgid "Sync would copy the following from remote to local:"
msgstr "Синхронизация скопирует это из удаленного места в локальное:"

#: ../duplicity/dup_main.py:1343
msgid "Sync would remove the following spurious local files:"
msgstr "Синхронизация удалит следующие  неизвестные файлы:"

#: ../duplicity/dup_main.py:1387
msgid "Unable to get free space on temp."
msgstr ""
"Не удалось узнать объем доступного пространства во временном каталоге."

#: ../duplicity/dup_main.py:1395
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr ""
"Во временно каталоге доступного %d, для резервного копирования нужно "
"примерно %d."

#: ../duplicity/dup_main.py:1398
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr ""
"Во временном каталоге доступно %d, для резервного копирования будет "
"использовано примерно %d."

#: ../duplicity/dup_main.py:1406
msgid "Unable to get max open files."
msgstr "Не удалось узнать максимальное количество открытых файлов."

#: ../duplicity/dup_main.py:1410
#, python-format
msgid ""
"Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr ""
"Максимальное количество открытых файлов %s слишком мало, Должно быть >= "
"1024.\n"
"Используйте 'ulimit -n 1024' или выше, чтобы исправить.\n"

#: ../duplicity/dup_main.py:1462
msgid ""
"RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr ""
"ПЕРЕЗАПУСК: Ошибка выгрузки первого тома перед завершением работы.\n"
"         Перезапуск невозможен...выполнение резервного копирования с начала."

#: ../duplicity/dup_main.py:1468
#, python-format
msgid ""
"RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr ""
"ПЕРЕЗАПУСК: Ошибка выгрузки томов %d дo %d перед завершением работы.\n"
"         Перезапуск резервного копирования в томе %d."

#: ../duplicity/dup_main.py:1475
#, python-format
msgid ""
"RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last "
"partial\n"
"         backup then restart the backup from the beginning."
msgstr ""
"ПЕРЕЗАПУСК: Невозможное состояние резервной копии: манифест содержит %d "
"томов, удалённый содержит %d томов.\n"
"         Перезапуск невозможен ... duplicity произведёт очистку последней "
"части\n"
"         резервной копии, затем запустит резервное копирования сначала."

#: ../duplicity/dup_main.py:1496
msgid ""
"\n"
"PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n"
"\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""

#: ../duplicity/dup_main.py:1519
#, python-format
msgid "Acquiring lockfile %s"
msgstr ""

#: ../duplicity/dup_main.py:1577
#, python-format
msgid "Last %s backup left a partial set, restarting."
msgstr ""
"Последняя %s резервная копия оставила частичный набор, выполняется "
"перезапуск."

#: ../duplicity/dup_main.py:1581
#, python-format
msgid "Cleaning up previous partial %s backup set, restarting."
msgstr ""
"Очистка предыдущего частичного %s набора резервного копирования, выполняется "
"перезапуск."

#: ../duplicity/dup_main.py:1593
msgid "Last full backup date:"
msgstr "Время последней полной резервной копии:"

#: ../duplicity/dup_main.py:1595
msgid "Last full backup date: none"
msgstr "Время последней полной резервной копии: нету"

#: ../duplicity/dup_main.py:1598
msgid "Last full backup is too old, forcing full backup"
msgstr ""
"Последняя полная резервная копия слишком старая, будет сделана полная "
"резервная копия"

#: ../duplicity/dup_main.py:1647
msgid ""
"When using symmetric encryption, the signing passphrase must equal the "
"encryption passphrase."
msgstr ""
"При использовании симметричного шифрования кодовая фраза для подписи должна "
"совпадать с кодовой фразой для шифрования."

#: ../duplicity/dup_time.py:63
#, python-format
msgid ""
"Bad interval string \"%s\"\n"
"\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr ""
"Строка с недопустимым интервалом \"%s\"\n"
"\n"
"Интервалы задаются на подобии 2Y (2 года) или 2h30m (2.5 часа).\n"
"Допустимые особые символы s (с.), m (м.), h (ч.), D(Д.), W (Н.), M (М.) и Y "
"(Г.).  \n"
"Обратитесь к руководству пользователя (man) для получения дополнительных "
"сведений."

#: ../duplicity/dup_time.py:69
#, python-format
msgid ""
"Bad time string \"%s\"\n"
"\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr ""
"Строка с недопустимым временем \"%s\"\n"
"\n"
"Допускается задание интервалов времени (например \"3D64s\"), строки \n"
"даты/времени формата w3, например \"2002-04-26T04:22:01-07:00\" (строки "
"типа\n"
"\"2002-04-26T04:22:01\" также допустимы - duplicity будет использовать\n"
"текущую временную зону) или обычные даты, например 2/4/1997 или 2001-04-23\n"
"(допустимы различные комбинации, но месяц всегда предшествует дню)."

#: ../duplicity/gpginterface.py:240
msgid "Threading not available -- zombie processes may appear"
msgstr ""

#: ../duplicity/gpginterface.py:707
#, python-format
msgid "GPG process %d terminated before wait()"
msgstr "Процесс GPG %d завершился до вызова wait()"

#: ../duplicity/lazy.py:355
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "Внимание: старый индекс %s >= нового индекса %s"

#: ../duplicity/lazy.py:430
#, python-format
msgid "Error '%s' processing %s"
msgstr "Ошибка '%s' при обработке %s"

#: ../duplicity/lazy.py:440
#, python-format
msgid "Skipping %s because of previous error"
msgstr "Пропуск %s из-за предыдущей ошибки"

#: ../duplicity/librsync.py:196
msgid ""
"basis_file must be a (true) file or an object whose file attribute is the "
"underlying true file object"
msgstr ""

#: ../duplicity/manifest.py:95
#, python-format
msgid ""
"Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr ""
"Критическая ошибка: Узел источника резервной копии изменён.\n"
"Текущий узел: %s\n"
"Предыдущий узел: %s"

#: ../duplicity/manifest.py:102
#, python-format
msgid ""
"Fatal Error: Backup source directory has changed.\n"
"Current directory: %s\n"
"Previous directory: %s"
msgstr ""
"Критическая ошибка: Исходный каталог резервной копии был изменён.\n"
"Текущий каталог: %s\n"
"Предыдущий каталон: %s"

#: ../duplicity/manifest.py:112
msgid ""
"Aborting because you may have accidentally tried to backup two different "
"data sets to the same remote location, or using the same archive directory.  "
"If this is not a mistake, use the --allow-source-mismatch switch to avoid "
"seeing this message"
msgstr ""
"Прекращение в связи с тем, что вы можете случайно попытаться создать "
"резервные копии двух отличающихся наборов данных, по одному адресу, в одно и "
"тоже удалённое расположение.  Если это ошибка, используйте параметр --allow-"
"source-mismatch для скрытия этого сообщения"

#: ../duplicity/manifest.py:214
#, python-format
msgid "Found manifest volume %s"
msgstr ""

#: ../duplicity/manifest.py:221
#, python-format
msgid "Found %s volumes in manifest"
msgstr ""

#: ../duplicity/manifest.py:238
#, python-format
msgid ""
"Manifest file '%s' is corrupt: File count says %d, File list contains %d"
msgstr ""

#: ../duplicity/manifest.py:257
msgid "Manifests not equal because different volume numbers"
msgstr "Манифесты не одинаковы в связи с отличающимися номерами томов"

#: ../duplicity/manifest.py:262
msgid "Manifests not equal because volume lists differ"
msgstr "Манифесты не одинаковы в связи с отличающимися списками томов"

#: ../duplicity/manifest.py:267
msgid "Manifests not equal because hosts or directories differ"
msgstr "Манифесты не одинаковы в связи с отличающимися узлами или каталогами"

#: ../duplicity/manifest.py:424
msgid "Warning, found extra Volume identifier"
msgstr "Внимание, найден дополнительный идентификатор тома"

#: ../duplicity/manifest.py:450
msgid "Other is not VolumeInfo"
msgstr "Другой не является VolumeInfo"

#: ../duplicity/manifest.py:453
msgid "Volume numbers don't match"
msgstr "Номера томов не соответствуют"

#: ../duplicity/manifest.py:456
msgid "start_indicies don't match"
msgstr "start_indicies не соответствует"

#: ../duplicity/manifest.py:459
msgid "end_index don't match"
msgstr "end_index не соответствует"

#: ../duplicity/manifest.py:466
msgid "Hashes don't match"
msgstr "Хэши не совпадают"

#: ../duplicity/patchdir.py:82 ../duplicity/patchdir.py:87
#, python-format
msgid "Patching %s"
msgstr "Внесение изменений в %s"

#: ../duplicity/patchdir.py:547
#, python-format
msgid "Error '%s' patching %s"
msgstr ""

#: ../duplicity/patchdir.py:622
#, python-format
msgid "Writing %s of type %s"
msgstr "Запись %s типа %s"

#: ../duplicity/path.py:115
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr ""

#: ../duplicity/path.py:244 ../duplicity/path.py:305
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "Внимание: у %s отрицательное mtime, принимается равным 0."

#: ../duplicity/path.py:369
msgid "Difference found:"
msgstr "Найдено отличие:"

#: ../duplicity/path.py:378
#, python-format
msgid "New file %s"
msgstr "Новый файл %s"

#: ../duplicity/path.py:381
#, python-format
msgid "File %s is missing"
msgstr "Файл %s отсутствует"

#: ../duplicity/path.py:384
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "Файл %%s относится к типу %s, а ожидался %s"

#: ../duplicity/path.py:390 ../duplicity/path.py:416
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr "Файл %%s имеет разрешения %s, а ожидалось %s"

#: ../duplicity/path.py:395
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "Файл %%s имеет mtime %s, а ожидалось %s"

#: ../duplicity/path.py:403
#, python-format
msgid "Data for file %s is different"
msgstr "Данные для файла %s отличаются"

#: ../duplicity/path.py:411
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "Символическая ссылка %%s указывает на %s, а ожидалось %s"

#: ../duplicity/path.py:420
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "Файл устройства %%s содержит номера %s, а ожидались %s"

#: ../duplicity/path.py:602
#, python-format
msgid "Making directory %s"
msgstr "Создаётся каталог %s"

#: ../duplicity/path.py:612
#, python-format
msgid "Deleting %s"
msgstr "Удаляется %s"

#: ../duplicity/path.py:621
#, python-format
msgid "Touching %s"
msgstr ""

#: ../duplicity/path.py:628
#, python-format
msgid "Deleting tree %s"
msgstr "Удаление дерева %s"

#: ../duplicity/robust.py:64
#, python-format
msgid "Error listing directory %s"
msgstr "Ошибка перечня каталога %s"

#: ../duplicity/selection.py:119
#, python-format
msgid "Skipping socket %s"
msgstr "Пропуск сокета %s"

#: ../duplicity/selection.py:123
#, python-format
msgid "Error initializing file %s"
msgstr "Ошибка инициализации файла %s"

#: ../duplicity/selection.py:127 ../duplicity/selection.py:152
#: ../duplicity/selection.py:452
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Ошибка доступа к возможно заблокированному файлу %s"

#: ../duplicity/selection.py:167
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Внимание: база %s не существует, выполняется продолжение"

#: ../duplicity/selection.py:170 ../duplicity/selection.py:188
#: ../duplicity/selection.py:191
#, python-format
msgid "Selecting %s"
msgstr "Выбор %s"

#: ../duplicity/selection.py:288
#, python-format
msgid ""
"Fatal Error: The file specification\n"
"    %s\n"
"cannot match any files in the base directory\n"
"    %s\n"
"Useful file specifications begin with the base directory or some\n"
"pattern (such as '**') which matches the base directory."
msgstr ""
"Критическая ошибка: Спецификация файла\n"
"    %s\n"
"не может соответствовать любым файлам в базовом каталоге\n"
"    %s\n"
"Полезные спецификации файла начинаются с базового каталога или\n"
"маски (например '**'), которая соответствует базовому каталогу."

#: ../duplicity/selection.py:297
#, python-format
msgid ""
"Fatal Error while processing expression\n"
"%s"
msgstr ""
"Критическая ошибка при обработке выражения\n"
"%s"

#: ../duplicity/selection.py:306
#, python-format
msgid ""
"Last selection expression:\n"
"    %s\n"
"only specifies that files be included.  Because the default is to\n"
"include all files, the expression is redundant.  Exiting because this\n"
"probably isn't what you meant."
msgstr ""
"Выражение последнего выделения:\n"
"    %s\n"
"только указывает на то, что файлы будут включены.  Так как\n"
"по умолчанию включаются все файлы, следовательно выражение избыточно.  \n"
"Выполнение выхода, так как возможно, что вероятно, это не то, что вы имели в "
"виду."

#: ../duplicity/selection.py:362
#, python-format
msgid "Reading globbing filelist %s"
msgstr "Чтение подстановочного списка файлов %s"

#: ../duplicity/selection.py:395
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Ошибка компилирования регулярного выражения %s"

#: ../duplicity/tempdir.py:160
#, python-format
msgid "Using temporary directory %s"
msgstr "Используется временный каталог %s"

#: ../duplicity/tempdir.py:204
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "Регистрация (mktemp) временного файла %s"

#: ../duplicity/tempdir.py:226
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "Регистрация (mkstemp) временного файла %s"

#: ../duplicity/tempdir.py:258
#, python-format
msgid "Forgetting temporary file %s"
msgstr "Удаление временного файла %s"

#: ../duplicity/tempdir.py:261
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr ""
"Попытка удалить неизвестный временный файл %s - похоже, что это ошибка в "
"программе."

#: ../duplicity/tempdir.py:280
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "Удаление всё ещё нужного временного файла %s"

#: ../duplicity/tempdir.py:283
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "Не удалось очистить временный файл %s"

#: ../duplicity/tempdir.py:288
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr ""
"Не удалось очистить временный каталог %s - похоже, что это ошибка в "
"программе."

#: ../duplicity/util.py:144
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr ""
"IGNORED_ERROR: Внимание: пропуск ошибки, как было обозначено в запросе: %s: "
"%s"

#: ../duplicity/util.py:211
#, python-format
msgid "Releasing lockfile %s"
msgstr ""
