# Belarusian translation for apt-listchanges
# Copyright (c) 2012 Rosetta Contributors and Canonical Ltd 2012
# This file is distributed under the same license as the apt-listchanges package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
msgid ""
msgstr ""
"Project-Id-Version: apt-listchanges\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2019-11-03 20:05+0100\n"
"PO-Revision-Date: 2012-01-05 11:17+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Belarusian <be@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2020-05-05 21:54+0000\n"
"X-Generator: Launchpad (build fbdff7602bd10fb883bf7e2ddcc7fd5a16f60398)\n"

#: ../apt-listchanges.py:62
#, python-format
msgid "Unknown frontend: %s"
msgstr ""

#: ../apt-listchanges.py:78
#, python-format
msgid "Cannot reopen /dev/tty for stdin: %s"
msgstr ""

#: ../apt-listchanges.py:133
#, python-format
msgid "News for %s"
msgstr "Навіны для %s"

#: ../apt-listchanges.py:135
#, python-format
msgid "Changes for %s"
msgstr "Змены для %s"

#: ../apt-listchanges.py:145
msgid "Informational notes"
msgstr "Дапаможныя нататкі"

#: ../apt-listchanges.py:152
msgid "apt-listchanges: News"
msgstr "apt-listchanges: Навіны"

#: ../apt-listchanges.py:153
msgid "apt-listchanges: Changelogs"
msgstr "apt-listchanges: Часопіс зменаў"

#: ../apt-listchanges.py:159
#, python-format
msgid "apt-listchanges: news for %s"
msgstr ""

#: ../apt-listchanges.py:160
#, python-format
msgid "apt-listchanges: changelogs for %s"
msgstr ""

#: ../apt-listchanges.py:166
msgid "Didn't find any valid .deb archives"
msgstr ""

#: ../apt-listchanges.py:183
#, python-format
msgid "%s: will be newly installed"
msgstr "%s: будзе ізноў усталяваны"

#: ../apt-listchanges.py:210
#, python-format
msgid "%(pkg)s: Version %(version)s has already been seen"
msgstr ""

#: ../apt-listchanges.py:214
#, python-format
msgid ""
"%(pkg)s: Version %(version)s is lower than version of related packages "
"(%(maxversion)s)"
msgstr ""

#: ../apt-listchanges.py:268
msgid "Binary NMU of"
msgstr ""

#: ../apt-listchanges.py:302
#, python-format
msgid "Received signal %d, exiting"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:55
msgid "Aborting"
msgstr "Спыненне"

#: ../apt-listchanges/apt_listchanges.py:60
#, python-format
msgid "Confirmation failed: %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:64
#, python-format
msgid "Mailing %(address)s: %(subject)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:83
#, python-format
msgid "Failed to send mail to %(address)s: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:92
#, python-format
msgid "The mail frontend needs an installed 'sendmail', using %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:98
#, python-format
msgid "The mail frontend needs an e-mail address to be configured, using %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:111
msgid "Available apt-listchanges frontends:"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:113
msgid "Choose a frontend by entering its number: "
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:122
#: ../apt-listchanges/apt_listchanges.py:431
#, python-format
msgid "Error: %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:124
#, python-format
msgid "Using default frontend: %s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:167
#, python-format
msgid "$DISPLAY is not set, falling back to %(frontend)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:187
#, python-format
msgid ""
"The gtk frontend needs a working python3-gi,\n"
"but it cannot be loaded. Falling back to %(frontend)s.\n"
"The error is: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:288
msgid "Do you want to continue? [Y/n] "
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:301
#: ../apt-listchanges/apt_listchanges.py:327
#: ../apt-listchanges/apt_listchanges.py:335
msgid "Reading changelogs"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:335
msgid "Done"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:368
#, python-format
msgid "Command %(cmd)s exited with status %(status)d"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:413
#, python-format
msgid "Found user: %(user)s, temporary directory: %(dir)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:459
#, python-format
msgid "Error getting user from variable '%(envvar)s': %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:465
msgid "Cannot find suitable user to drop root privileges"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:491
#, python-format
msgid ""
"None of the following directories is accessible by user %(user)s: %(dirs)s"
msgstr ""

#: ../apt-listchanges/apt_listchanges.py:521
msgid "press q to quit"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:88
#, python-format
msgid "Unknown configuration file option: %s"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:101
msgid "Usage: apt-listchanges [options] {--apt | filename.deb ...}\n"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:107
#, python-format
msgid ""
"Unknown argument %(arg)s for option %(opt)s.  Allowed are: %(allowed)s."
msgstr ""

#: ../apt-listchanges/ALCConfig.py:119
#, python-format
msgid "%(deb)s does not have '.deb' extension"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:122
#, python-format
msgid "%(deb)s does not exist or is not a file"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:125
#, python-format
msgid "%(deb)s is not readable"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:216
msgid "--since=<version> and --show-all are mutually exclusive"
msgstr ""

#: ../apt-listchanges/ALCConfig.py:224
msgid "--since=<version> expects a path to exactly one .deb archive"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:119 ../apt-listchanges/DebianFiles.py:128
#, python-format
msgid "Error processing '%(what)s': %(errmsg)s"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:337
#, python-format
msgid "Ignoring `%s' (seems to be a directory!)"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:410
#, python-format
msgid "Calling %(cmd)s to retrieve changelog"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:414
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; 'apt-get changelog' failed "
"with: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/DebianFiles.py:420
#, python-format
msgid ""
"Unable to retrieve changelog for package %(pkg)s; could not run 'apt-get "
"changelog': %(errmsg)s"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:40
msgid "apt-listchanges: Reading changelogs"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:41
msgid "Reading changelogs. Please wait."
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:74
msgid "Continue Installation?"
msgstr ""

#: ../apt-listchanges/AptListChangesGtk.py:75
msgid ""
"Select <i>yes</i> to continue with the installation.\n"
"Select <i>no</i> to abort the installation."
msgstr ""

#: ../apt-listchanges/ALCApt.py:55
msgid "APT pipeline messages:"
msgstr ""

#: ../apt-listchanges/ALCApt.py:63
msgid "Packages list:"
msgstr ""

#: ../apt-listchanges/ALCApt.py:71
msgid ""
"APT_HOOK_INFO_FD environment variable is not defined\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD set to 20?)"
msgstr ""

#: ../apt-listchanges/ALCApt.py:77
msgid "Invalid (non-numeric) value of APT_HOOK_INFO_FD environment variable"
msgstr ""

#: ../apt-listchanges/ALCApt.py:80
#, python-format
msgid "Will read apt pipeline messages from file descriptor %d"
msgstr ""

#: ../apt-listchanges/ALCApt.py:83
msgid ""
"Incorrect value (0) of APT_HOOK_INFO_FD environment variable.\n"
"If the warning persists after restart of the package manager (e.g. "
"aptitude),\n"
"please check if the /etc/apt/apt.conf.d/20listchanges file was properly "
"updated."
msgstr ""

#: ../apt-listchanges/ALCApt.py:88
msgid ""
"APT_HOOK_INFO_FD environment variable is incorrectly defined\n"
"(Dpkg::Tools::Options::/usr/bin/apt-listchanges::InfoFD should be greater "
"than 2)."
msgstr ""

#: ../apt-listchanges/ALCApt.py:94
#, python-format
msgid "Cannot read from file descriptor %(fd)d: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/ALCApt.py:100
msgid ""
"Wrong or missing VERSION from apt pipeline\n"
"(is Dpkg::Tools::Options::/usr/bin/apt-listchanges::Version set to 2?)"
msgstr ""

#: ../apt-listchanges/ALCLog.py:30 ../apt-listchanges/ALCLog.py:36
#, python-format
msgid "apt-listchanges: %(msg)s"
msgstr ""

#: ../apt-listchanges/ALCLog.py:33
#, python-format
msgid "apt-listchanges warning: %(msg)s"
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:55
msgid ""
"Path to the seen database is unknown.\n"
"Please either specify it with --save-seen option\n"
"or pass --profile=apt to have it read from the configuration file."
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:66
#, python-format
msgid "Database %(db)s does not end with %(ext)s"
msgstr ""

#: ../apt-listchanges/ALCSeenDb.py:75
#, python-format
msgid "Database %(db)s failed to load: %(errmsg)s"
msgstr ""

#: ../apt-listchanges/apt-listchanges.ui:13
msgid "List the changes"
msgstr ""

#: ../apt-listchanges/apt-listchanges.ui:43
msgid ""
"The following changes are found in the packages you are about to install:"
msgstr ""
